controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin :
    path : '/admin'
    controller : App\Controller\Admin\DashboardController::index

app_logout :
    path : '/logout'
    controller : App\Controller\SecurityController::logout

app_login :
    path : '/'
    controller : App\Controller\Admin\DashboardController::login